sudo: required

services: docker

before_install:
  - docker-compose up --build -d

script:
  - docker-compose exec --env 'RAILS_ENV2=test' web rails db:create
  - docker-compose exec --env 'RAILS_ENV2=test' web rails db:migrate
  - docker-compose exec --env 'RAILS_ENV2=test' web rails test